name: identity-example size diff
on:
  pull_request:
jobs:
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run scripts
        run: ./scripts/run.rb
